spring:
  application.name: rennes.tech

  jpa:
    open-in-view: false
    properties:
      #tweaks to gain memory
      hibernate.query.plan_cache_max_size: 512
      hibernate.query.in_clause_parameter_padding: true

  jmx.enabled: false
  threads.virtual.enabled: true

  liquibase.changeLog: classpath:/db/changelog/db.changelog-master.xml
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST}:${POSTGRESQL_PORT}/${POSTGRESQL_DB}?currentSchema=${POSTGRESQL_SCHEMA}
    username: ${POSTGRESQL_USER}
    password: ${POSTGRESQL_PASSWORD}


management.server.port: 8081

server:
  forward-headers-strategy: FRAMEWORK
  tomcat.remoteip:
    remote_ip_header: X-Forwarded-For
    protocol_header: X-Forwarded-Proto

springdoc.packages-to-scan: org.breizhcamp.rennes.tech.application.rest

rennes.tech.back:
  sync.enabled: true
  meetup:
    base-url: https://www.meetup.com
    query-hash: ${MEETUP_QUERY_HASH:066e3709c68718d5ce9dd909e979ac70f99835fb3722cef77756ded808d5ca08}
