spring:
  application.name: rennes.tech

  jpa.open-in-view: false
  liquibase.changeLog: classpath:/db/changelog/db.changelog-master.xml
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST}:${POSTGRESQL_PORT}/${POSTGRESQL_DB}?currentSchema=${POSTGRESQL_SCHEMA}
    username: ${POSTGRESQL_USER}
    password: ${POSTGRESQL_PASSWORD}


management.server.port: 8081

server:
  forward-headers-strategy: FRAMEWORK
  tomcat.remoteip:
    remote_ip_header: X-Forwarded-For
    protocol_header: X-Forwarded-Proto


rennes.tech.back:
  sync.enabled: true
  meetup:
    base-url: https://www.meetup.com
